site_name: Bootstrap v5
use_directory_urls: false

plugins:
     - search
#     - pdf-export:
#        combined: true

nav:
- Contenidos: 'README.md'
- Introducción a HTML: 'capitulo_html.md'
    - Editores HTML: 'capitulo_html_editores.md'
    - Sintaxis del lenguaje: 'capitulo_html_etiquetas.md'
    - Estructura básica de una Web: 'capitulo_html_estructura_basica.md'
    - Elementos de la cabecera: 'capitulo_html_elementos_de_la_cabecera.md'
    - Etiquetas básicas: 'capitulo_html_etiquetas_basicas.md'
    - Listas: 'capitulo_html_listas.md'
    - Tablas: 'capitulo_html_tablas.md'
    - Cajas, etiqueta DIV: 'capitulo_html_cajas.md'
    - Enlaces: 'capitulo_html_enlaces.md'
    - Imágenes: 'capitulo_html_imagenes.md'
    - Formularios: 'capitulo_html_formularios.md'
    - Eventos: 'capitulo_html_eventos.md'
    - Símbolos HTML: 'capitulo_html_simbolos.md'
- Introducción a CSS: 'capitulo_css.md'
    - Adjuntar una hoja de estilo: 'capitulo_css_adjuntar_una_hoja_de_estilo.md'
    - Definición de estilos para etiquetas HTML: 'capitulo_css_definicion_de_estilos.md'
    - Identificadores y clases: 'capitulo_css_identificadores_y_clases.md'
    - Estilos CSS básicos: 'capitulo_css_estilos_basicos.md'
        - Estilos para textos: 'capitulo_css_estilos_para_textos.md'
        - Estilos para párrafos: 'capitulo_css_estilos_para_parrafos.md'
        - Estilos para fondos: 'capitulo_css_estilos_para_fondos.md'
        - Estilos para cajas: 'capitulo_css_estilos_para_cajas.md'
    - Pseudo-clases: 'capitulo_css_pseudo-clases.md'
    - Capas: 'capitulo_css_capas.md'
    - Ejemplo de uso: 'capitulo_css_ejemplo.md'
- Introducción a HTML 5: 'capitulo_html5.md'
    - Navegadores que lo soportan: 'capitulo_html5_navegadores.md'
    - Doctype: 'capitulo_html5_doctype.md'
    - Estructura semántica: 'capitulo_html5_estructura_semantica.md'
    - Formularios: 'capitulo_html5_formularios.md'
    - Etiqueta Mark: 'capitulo_html5_mark.md'
    - Canvas: 'capitulo_html5_canvas.md'
    - Audio: 'capitulo_html5_audio.md'
    - Vídeo: 'capitulo_html5_video.md'
    - Geolocalización: 'capitulo_html5_geolocalizacion.md'
    - Almacenamiento Offline: 'capitulo_html5_almacenamiento_offline.md'
    - Detectar funcionalidades de HTML 5: 'capitulo_html5_deteccion.md'
- Introducción a CSS 3: 'capitulo_css3.md'
    - Nuevos selectores de atributos: 'capitulo_css3_nuevos_selectores.md'
    - Nuevas pseudo-clases: 'capitulo_css3_nuevas_pseudo-clases.md'
    - Color: 'capitulo_css3_color.md'
    - Bordes: 'capitulo_css3_bordes.md'
    - Fondos: 'capitulo_css3_fondos.md'
    - Texto: 'capitulo_css3_texto.md'
    - Columnas: 'capitulo_css3_columnas.md'
    - Modelo de caja básico: 'capitulo_css3_modelo_de_caja_basico.md'
    - Transiciones: 'capitulo_css3_transiciones.md'
    - Transformaciones: 'capitulo_css3_transformaciones.md'
- Introducción a JavaScript: 'capitulo_javascript.md'
    - Inclusión de JavaScript en HTML: 'capitulo_javascript_inclusion_en_html.md'
    - Etiqueta noscript: 'capitulo_javascript_etiqueta_noscript.md'
    - Consideraciones sobre el lenguaje: 'capitulo_javascript_consideraciones.md'
    - Variables: 'capitulo_javascript_variables.md'
    - Operadores: 'capitulo_javascript_operadores.md'
    - Estructuras de control de flujo: 'capitulo_javascript_control_de_flujo.md'
    - Funciones útiles: 'capitulo_javascript_funciones_utiles.md'
    - Funciones: 'capitulo_javascript_funciones.md'
    - DOM: 'capitulo_javascript_dom.md'
    - Eventos: 'capitulo_javascript_eventos.md'
    - Detección de errores: 'capitulo_javascript_deteccion_de_errores.md'
- Más información: 'capitulo_mas_informacion.md'
- Ejercicios 1: 'capitulo_ejercicios_1.md'
- Ejercicios 2: 'capitulo_ejercicios_2.md'


theme:
    language: es
    name: 'material'
    palette:
        primary: 'Indigo'
        accent: 'Indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    logo: 'assets/logo.png'

# Ponemos como idioma de búsqueda el inglés
# para conseguir que busque correctamente
# todas las palabras en castellano, sin eliminar
# los excesivos derivados que se definen en
# https://github.com/MihaiValentin/lunr-languages/blob/master/lunr.es.js

extra:
    search:
        language: 'en'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


#      - pymdownx.superfences
#     - pymdownx.arithmatex
markdown_extensions:
     - admonition
     - codehilite:
        linenums: true
     - footnotes
     - meta
     - sane_lists
     - toc:
       permalink: true
       toc_depth: 3
